# Generated by Django 4.1.5 on 2023-01-21 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="assigned_users",
            field=models.ForeignKey(
                default="",
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
