# Generated by Django 4.1.5 on 2023-01-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_alter_application_assigned_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="Bachelor_Marksheet",
        ),
        migrations.RemoveField(
            model_name="application",
            name="Diploma_Marksheet",
        ),
        migrations.RemoveField(
            model_name="application",
            name="Language_Exam",
        ),
        migrations.RemoveField(
            model_name="application",
            name="Lor",
        ),
        migrations.RemoveField(
            model_name="application",
            name="Master_Marksheet",
        ),
        migrations.RemoveField(
            model_name="application",
            name="Resume",
        ),
        migrations.RemoveField(
            model_name="application",
            name="Sop",
        ),
        migrations.RemoveField(
            model_name="application",
            name="Twelveth_Marksheet",
        ),
        migrations.RemoveField(
            model_name="application",
            name="assigned_users",
        ),
        migrations.RemoveField(
            model_name="application",
            name="status",
        ),
    ]
