# Generated by Django 4.1.5 on 2023-01-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_alter_application_bachelor_marksheet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="Bachelor_Marksheet",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="application",
            name="Diploma_Marksheet",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="application",
            name="Language_Exam",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="application",
            name="Lor",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="application",
            name="Master_Marksheet",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="application",
            name="Resume",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="application",
            name="Sop",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="application",
            name="Tenth_Marksheet",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="application",
            name="Twelveth_Marksheet",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
