# Generated by Django 4.1.5 on 2023-02-08 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0007_delete_notification"),
        ("application", "0006_alter_application_bachelor_marksheet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application",
                to="enquiry.enquiry",
            ),
        ),
    ]
