# Generated by Django 4.1.7 on 2023-02-27 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0007_alter_application_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='added_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_byForApplication', to=settings.AUTH_USER_MODEL),
        ),
    ]
