# Generated by Django 4.1.7 on 2023-03-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_application_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Bachelor_Marksheet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Diploma_Marksheet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Language_Exam',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Lor',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Master_Marksheet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Sop',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Tenth_Marksheet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Twelveth_Marksheet',
        ),
    ]
