# Generated by Django 4.1.7 on 2023-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_application_tenth_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Tenth_Marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
