# Generated by Django 4.1.7 on 2023-03-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_application_file_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='application',
            name='Bachelor_Marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='Diploma_Marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='Language_Exam',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='Lor',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='Master_Marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='Resume',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='Sop',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='application',
            name='Twelveth_Marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Tenth_Marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
