# Generated by Django 4.1.7 on 2023-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_application_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
