# Generated by Django 4.1.5 on 2023-01-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
    ]
