# Generated by Django 4.1.7 on 2023-02-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application_status',
            options={'verbose_name': 'Application Status', 'verbose_name_plural': 'Application Status'},
        ),
        migrations.AlterModelOptions(
            name='course_levels',
            options={'verbose_name': 'Course Level'},
        ),
        migrations.AlterModelOptions(
            name='course_requirements',
            options={'verbose_name': 'Course Requirement', 'verbose_name_plural': 'Course Requirements'},
        ),
        migrations.AlterModelOptions(
            name='current_education',
            options={'verbose_name': 'Current Education', 'verbose_name_plural': 'Current Education'},
        ),
        migrations.AlterModelOptions(
            name='documents_required',
            options={'verbose_name': 'Documents required', 'verbose_name_plural': 'Documents required'},
        ),
        migrations.AlterModelOptions(
            name='enquiry_status',
            options={'verbose_name': 'Enquiry Status', 'verbose_name_plural': 'Enquiry Status'},
        ),
        migrations.AddField(
            model_name='application_status',
            name='desciption',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='enquiry_status',
            name='desciption',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
