# Generated by Django 4.1.7 on 2023-03-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_application_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_status',
            name='App_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry_status',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
