# Generated by Django 4.1.7 on 2023-03-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_agent_appointment_boardnoteligible_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityrequirements',
            name='course_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.course_levels'),
        ),
    ]
