# Generated by Django 4.1.7 on 2023-05-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_universityrequirements_app_fees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityRequirements',
        ),
    ]
