# Generated by Django 4.1.5 on 2023-01-20 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("Active", models.BooleanField()),
                (
                    "course_levels",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.course_levels",
                    ),
                ),
                (
                    "course_requirements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.course_requirements",
                    ),
                ),
                (
                    "documents_required",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.documents_required",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.intake"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("univ_name", models.CharField(max_length=100)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("univ_desc", models.CharField(max_length=1000)),
                ("univ_logo", models.ImageField(upload_to="media")),
                ("univ_phone", models.CharField(blank=True, max_length=10)),
                ("univ_email", models.EmailField(blank=True, max_length=254)),
                ("univ_website", models.URLField(blank=True)),
                (
                    "assigned_users",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Universities",
            },
        ),
        migrations.CreateModel(
            name="enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("student_phone", models.CharField(max_length=10)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_address", models.TextField()),
                (
                    "country_interested",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "assigned_users",
                    models.ForeignKey(
                        default="",
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course_interested",
                    models.ForeignKey(
                        limit_choices_to={"Active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="enquiry.course",
                    ),
                ),
                (
                    "current_education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.current_education",
                    ),
                ),
                (
                    "enquiry_status",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.enquiry_status",
                    ),
                ),
                (
                    "intake_interested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.intake"
                    ),
                ),
                (
                    "level_applying_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.course_levels",
                    ),
                ),
                (
                    "university_interested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enquiry.university",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiries",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enquiry.university"
            ),
        ),
    ]
