# Generated by Django 4.1.5 on 2023-01-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_country"),
        ("enquiry", "0003_alter_enquiry_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="country_interested",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="master.country"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="master.country"
            ),
        ),
    ]
