# Generated by Django 4.1.5 on 2023-02-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0006_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
