# Generated by Django 4.1.7 on 2023-03-21 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0011_enquiry_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='married',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='False', max_length=50, verbose_name='Married'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='passport_number',
            field=models.CharField(default='0000', max_length=50, verbose_name='Passport Number'),
        ),
    ]
