# Generated by Django 4.1.7 on 2023-03-22 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_application_status_app_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0012_enquiry_dob_enquiry_married_enquiry_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='assigned_users',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course_interested',
            field=models.ForeignKey(blank=True, limit_choices_to={'Active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='enquiry.course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='current_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.current_education'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='level_applying_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.course_levels'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=50, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='passport_number',
            field=models.CharField(blank=True, default='0000', max_length=50, null=True, verbose_name='Passport Number'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiry.university'),
        ),
    ]
