# Generated by Django 4.1.7 on 2023-03-22 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0005_alter_application_status_app_status_and_more'),
        ('enquiry', '0013_alter_enquiry_assigned_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='assigned_users',
            field=models.ForeignKey(default='', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='country_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.country'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='intake_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.intake'),
        ),
    ]
