# Generated by Django 4.1.7 on 2023-03-22 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0014_alter_enquiry_assigned_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='assigned_users',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
