# Generated by Django 4.1.7 on 2023-03-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0016_university_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course_interested',
            field=models.ForeignKey(blank=True, limit_choices_to={'Active': True, 'university__active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='enquiry.course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquiry.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='univ_logo',
            field=models.ImageField(blank=True, upload_to='universitylogo'),
        ),
    ]
