# Generated by Django 4.1.7 on 2023-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0017_alter_enquiry_course_interested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='univ_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
