# Generated by Django 4.1.7 on 2023-03-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_universityrequirements_app_fees_and_more'),
        ('enquiry', '0018_alter_university_univ_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.enquiry_status'),
        ),
    ]
