# Generated by Django 4.1.7 on 2023-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0021_alter_enquiry_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='student_phone',
            field=models.CharField(max_length=20),
        ),
    ]
