# Generated by Django 4.1.7 on 2023-05-16 12:15

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_delete_universityrequirements'),
        ('enquiry', '0022_alter_enquiry_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='academic_requirement',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=' Academic Requirement General(Percent)'),
        ),
        migrations.AddField(
            model_name='university',
            name='accept_case_from_high_risk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Accept Case from High Risk'),
        ),
        migrations.AddField(
            model_name='university',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='app_fees',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Application Fees'),
        ),
        migrations.AddField(
            model_name='university',
            name='appointment_of_agent',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('University Discretion', 'University Discreation')], max_length=50, null=True, verbose_name='Appointment of agent'),
        ),
        migrations.AddField(
            model_name='university',
            name='board_not_eligible',
            field=models.ManyToManyField(to='master.boardnoteligible', verbose_name='Region or Boards not Eligible for English Waiver'),
        ),
        migrations.AddField(
            model_name='university',
            name='campus',
            field=models.ManyToManyField(to='master.campus'),
        ),
        migrations.AddField(
            model_name='university',
            name='change_of_agent',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('University Discretion', 'University Discreation')], max_length=50, null=True, verbose_name='Change of agent'),
        ),
        migrations.AddField(
            model_name='university',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.course_levels'),
        ),
        migrations.AddField(
            model_name='university',
            name='credibility_interview',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=True, max_length=10, verbose_name='Credibility Interview'),
        ),
        migrations.AddField(
            model_name='university',
            name='dependency_acceptance',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=50, verbose_name='Dependent Acceptance'),
        ),
        migrations.AddField(
            model_name='university',
            name='dependent_acceptance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dependent Acceptance'),
        ),
        migrations.AddField(
            model_name='university',
            name='deposit_for_CAS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Deposit for CAS'),
        ),
        migrations.AddField(
            model_name='university',
            name='english_requirement',
            field=models.ManyToManyField(to='master.english_requirments'),
        ),
        migrations.AddField(
            model_name='university',
            name='english_test',
            field=models.ManyToManyField(to='master.englishtest', verbose_name='English Test Accepted'),
        ),
        migrations.AddField(
            model_name='university',
            name='english_waiver',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='English Waiver-(Percent)'),
        ),
        migrations.AddField(
            model_name='university',
            name='finance_for_CAS',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=True, max_length=10, verbose_name='Finance for CAS'),
        ),
        migrations.AddField(
            model_name='university',
            name='gap',
            field=models.PositiveIntegerField(default=0, verbose_name='Education GAP (In years)'),
        ),
        migrations.AddField(
            model_name='university',
            name='general_documents',
            field=models.ManyToManyField(related_name='university_requirements', to='master.documents_required'),
        ),
        migrations.AddField(
            model_name='university',
            name='general_visa_refusal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='General Visa Refusal type'),
        ),
        migrations.AddField(
            model_name='university',
            name='ielts_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[master.models.validate_negatives], verbose_name='IELTS'),
        ),
        migrations.AddField(
            model_name='university',
            name='intake',
            field=models.ManyToManyField(to='master.intake'),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.ManyToManyField(to='master.location', verbose_name='Locations'),
        ),
        migrations.AddField(
            model_name='university',
            name='mandatory_docs',
            field=models.ManyToManyField(related_name='university_requirement', to='master.documents_required', verbose_name='Mandatory Document'),
        ),
        migrations.AddField(
            model_name='university',
            name='offer_timeline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Offer time line'),
        ),
        migrations.AddField(
            model_name='university',
            name='others',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Others'),
        ),
        migrations.AddField(
            model_name='university',
            name='payment_option',
            field=models.ManyToManyField(to='master.payment_option', verbose_name='Payment Option'),
        ),
        migrations.AddField(
            model_name='university',
            name='placement_option',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=50, verbose_name='Placement Option '),
        ),
        migrations.AddField(
            model_name='university',
            name='pte',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[master.models.validate_negatives], verbose_name='PTE'),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Scholarship'),
        ),
        migrations.AddField(
            model_name='university',
            name='student_visa_refusal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Visa Refusal type'),
        ),
        migrations.AddField(
            model_name='university',
            name='tofel',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[master.models.validate_negatives], verbose_name='TOFEL'),
        ),
        migrations.AddField(
            model_name='university',
            name='web_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
